FROM python:3.7-slim

WORKDIR /app

COPY requirements.txt .

RUN apt-get update
RUN apt-get install -y libpq-dev gcc

RUN pip3 install -r /api_yamdb/requirements.txt --no-cache-dir

COPY . .

CMD ["gunicorn", "api_yamdb.wsgi:application", "--bind", "0:8000"]